---
group: stable
dist: trusty
language: python
python: "2.7"

env:
  - ANSIBLE_INSTALL_VERSION=2.1.0

before_install:
  # Update the system
  - sudo apt-get update -qq

install:
  # Install ansible
  - pip install ansible-lint
  - pip install ansible==${ANSIBLE_INSTALL_VERSION}

script:
  # ansible-lint validation
  - ansible-lint {defaults,meta,tasks}/*.yml
