---
- name: Verify if selinux is enabled
  shell: getenforce
  register: sestatus
  changed_when: False

- name: Disable selinux now
  command: setenforce 0
  when: sestatus.stdout.find('Enforcing') == 0

- name: Install system package
  yum: name={{ item }} state=installed
  with_items: ['parted', 'lvm2']

- name: Create mount point for chroot environment
  file: path={{ disk2mnt }} state=directory owner=root group=root mode=0755

- name: Check there is a second EBS Volume
  shell: ls -lh {{ disk2dev }}

- name: Create new partition table on the second EBS Volume
  shell: parted --script {{ disk2dev }} mklabel msdos

- name: Create boot partition on the new disk
  shell: parted --script {{ disk2dev }} mkpart primary ext3 1MB {{ bootsize }}

- name: Create lvm partition on the new disk
  shell: parted --script {{ disk2dev }} mkpart primary ext4 {{ bootsize }} 100%

- name: Set partition flags on boot
  shell: parted --script {{ disk2dev }} set 1 boot on

- name: Set partition flags on lvm
  shell: parted --script {{ disk2dev }} set 2 lvm on

- name: Create boot filesystem
  shell: mkfs.ext3 -L boot {{ disk2dev }}1

- name: Create LVM Physical-Volume
  shell: pvcreate -ff --yes {{ disk2dev }}2

- name: Create LVM Volume-Group
  shell: vgcreate {{ disk2vg }} {{ disk2dev }}2

- name: Create LVM Logical-Volume
  shell: lvcreate --wipesignatures=y --zero=y --name=root --size={{ rootsize }} {{ disk2vg }}

- name: Create root filesystem
  shell: mkfs.ext4 -L root /dev/{{ disk2vg }}/root

- name: Mount new root filesystem
  shell: mount /dev/disk/by-label/root {{ disk2mnt }}

- name: Create important top-level directories
  shell: mkdir -p {{ disk2mnt }}/{boot,dev,proc,sys,etc}

- name: Mount boot filesystem
  shell: mount /dev/disk/by-label/boot {{ disk2mnt }}/boot

- name: Create important directories
  shell: mkdir -p {{ disk2mnt }}{{ item }}
  with_items:
    - /var/lib/rpm
    - /etc/sysconfig

- name: Create /etc/resolv.conf for chrooted programs
  shell: cp -a /etc/resolv.conf {{ disk2mnt }}/etc/resolv.conf

- name: Initiate RPM database in chroot environment
  shell: rpm --rebuilddb --root={{ disk2mnt }}

- name: Import GPG keys for CentOS yum repository
  shell: rpm --import --root={{ disk2mnt }} {{ gpgkey_centos7 }}

- name: Install CentOS release package (centos-release-xxx.rpm)
  shell: rpm -i --root={{ disk2mnt }} --nodeps {{ releasepkg }}

- name: Prepare chroot environment mounts
  shell: mount --bind /{{ item }} {{ disk2mnt }}/{{ item }}
  with_items: ['proc', 'dev', 'sys']

- name: Install base of the system in chroot environment
  shell: yum --releasever=7 --installroot={{ disk2mnt }} install -y rpm-build yum

- name: Install base package groups in chroot environment
  shell: chroot {{ disk2mnt }} /bin/yum -y groupinstall base core

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest={{ disk2mnt }}/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest={{ disk2mnt }}/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

- name: Install cloud-init and cloud-utils-growpart
  shell: chroot {{ disk2mnt }} /bin/yum -y install cloud-init cloud-utils-growpart

- name: Install aws tools which may be required to initialize instances
  shell: chroot {{ disk2mnt }} /bin/yum -y install awscli python2-boto rubygem-aws-sdk-resources

- name: Create important configuration files
  template: src={{ item }}.j2 dest={{ disk2mnt }}/{{ item }}
  with_items:
    - etc/sysconfig/network-scripts/ifcfg-eth0
    - etc/sysconfig/network
    - etc/ssh/sshd_config
    - etc/cloud/cloud.cfg
    - etc/selinux/config
    - etc/default/grub
    - etc/fstab

- name: Install kernel and grub packages
  shell: chroot {{ disk2mnt }} /bin/yum -y install kernel kernel-devel grub2 grubby grub2-tools

- name: Generate grub2 configuration file
  shell: chroot {{ disk2mnt }} /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Execute grub2 installer
  shell: chroot {{ disk2mnt }} /sbin/grub2-install {{ disk2dev }}

- name: Clean installation packages
  shell: chroot {{ disk2mnt }} /bin/yum clean all

- name: Unmount chroot environment mounts
  shell: umount {{ disk2mnt }}/{{ item }}
  with_items: ['proc', 'dev', 'sys', 'boot']

- name: Unmount chroot environment root
  shell: umount {{ disk2mnt }}

- name: Stop accessing LVM Logical-Volumes
  shell: vgchange -an {{ disk2vg }}
