---
- import_tasks: 01_create.yml
  tags: ['centos-ami-builder','centos-ami-builder-create']
- import_tasks: 02_install.yml
  delegate_to: ami_builder
  become: true
  tags: ['centos-ami-builder','centos-ami-builder-install']
- import_tasks: 03_image.yml
  tags: ['centos-ami-builder','centos-ami-builder-image']
- import_tasks: 04_cleanup.yml
  tags: ['centos-ami-builder','centos-ami-builder-cleanup']
